# Generated by Django 3.0.8 on 2020-10-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20201027_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtickets',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
